ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor_eagle/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor_eagle/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
